### ISSUE TITLE
Add interact support

### ISSUE THREAD

**Issue by Alexey1Gavrilov** [Alexey1Gavrilov/ExpectIt#21]
It would be good to add "interact" support since competitive libraries have it. For example, ExpectJ - http://expectj.bzr.sourceforge.net/bzr/expectj/trunk/annotate/head%3A/src/main/java/expectj/Spawn.java

**Comment by tianchengbaihe** [comment]
By the way, does it mean it will support this later:

in expect, we write like this
expect {
  "a" {...}
  "b" {...}
}

Thanks.

**Comment by Alexey1Gavrilov** [comment]
Yes, I'm planning to make similar to expect. Hopefully I can find time for this.

**Comment by Alexey1Gavrilov** [comment]
Here is the proposed syntax:

            expect.interact()
                    .when(contains("abc")).then(r -> System.out.println("A"))
                    .when(contains("xyz")).then(r -> System.err.println("B"))
                    .until(contains("exit"));
