### ISSUE TITLE
Bug: Sometimes sendLines are send before connection is initialized

### ISSUE THREAD

**Issue by awilhelmer** [Alexey1Gavrilov/ExpectIt#37]
Hello,

first of all: I'm using your framework and i think its a great alternative to write interactive small console based programs in java, without the usage of incredible bash scripts.

I noticed on some Ubuntu machines, that all sendLines commands are send before the connection or process is initialized over SSH Jsch Framework and the execution of Runtime.exec("/bin/sh") .

**Comment by Alexey1Gavrilov** [comment]
Can you provide a code example? 

Basically, the sendLine command is very simple. It just writes data to the underlying output stream. 
Have you tried to wrap the output stream with a buffered output stream? It may help.

**Comment by awilhelmer** [comment]
I added  expect.expect(Matchers.contains("#"));  that resolved the problem. But now the program is OS or prompt dependent.
```
expect = new ExpectBuilder().withOutput(channel.getOutputStream()).withInputs(channel.getInputStream(), channel.getExtInputStream())
                  .withEchoOutput(System.out).withEchoInput(System.err).withExceptionOnFailure().build();

expect.expect(Matchers.contains("#"));

expect.sendLine(String.format("cd %s", PropertiesHandler.inst().getPath()));
```

**Comment by Alexey1Gavrilov** [comment]
Good to know that the issue has been resolved.

If your requirement is to make the program prompt independent, you can consider modifying the command line prompt by setting the environment variable PS1 in the begging of the session.

Here is a link for the reference: https://en.wikipedia.org/wiki/Command-line_interface#Command_prompt
