### ISSUE TITLE
Matchers.anyString() only returns first 1024 characters present on the inputStream

### ISSUE THREAD

**Issue by tomaskir** [Alexey1Gavrilov/ExpectIt#41]
What I want:
I want to get all of the data present on the InputStream after 4 seconds.
This is arbitrary data that is later parsed, so I cant use any particular regex to match it.

Problem I am running into:
Assume we have a fully built expect object.

    expect = new ExpectBuilder()
        ...
        .withInputs(fromDevice)
        .withInputs(toDevice)
        ...
        .build();

Now I want to get all the data the device outputs in the 4 seconds after I send a key-word:

    expect.sendLine("give me data");
    
    Thread.sleep(4000);

    data = expect.withTimeout(1, TimeUnit.MILLISECONDS).expect(Matchers.anyString()).group();

The problem is that `data` only contains 1024 characters, not ALL of the data that is really on the `fromDevice` InputStream.

I have traced the problem to `SingleInputExpect`, where there is an internal buffer of 1024. So data is 'chunked' into chunks of 1024, and each one is compared against the matcher. The problem is that `anyString()` matcher matches straight away.

I would expect that the correct behaviour in this case is not to return the first 1024 characters, but the entire 'content' present on the InputStream.

Any comments on this behaviour, or how to achieve what I want to do here?

Thanks!

**Comment by Alexey1Gavrilov** [comment]
Well, anyString() matches immediately when at least one character has been received.  It does't suite you needs.

You can a custom matcher which will match when exactly 4 seconds have elapsed. Something like:

```
 public class TimeMatcher implements Matcher<Result> {
        private final long startedAt;
        private final long timeoutMillis;

        public TimeMatcher(final long timeoutMillis) {
            this.startedAt = System.currentTimeMillis();
            this.timeoutMillis = timeoutMillis;
        }

        @Override
        public Result matches(final String input, final boolean isEof) {
            return System.currentTimeMillis() - startedAt > timeoutMillis  
                    ? success(input, "", input)
                    : failure(input, false);
        }
    }
```
and then use it as follows:

```
expect.expect(new TimeMatcher(4000L)).group();
 ```
