### ISSUE TITLE
100% CPU usage by SingleInputExpect.expect()

### ISSUE THREAD

**Issue by tomaskir** [Alexey1Gavrilov/ExpectIt#43]
Hello,

We have an issue where `expect.expect(...)` can consume 100% CPU.
Here is (what I hope is) a detailed description of the situation.

Some devices which we connect to, trying to connect to them results in `Connection closed by foreign host`. Here is how it looks like connecting with Telnet in Linux:
```
tomas@system:~$ telnet 1.2.3.4 333
Trying 1.2.3.4...
Connected to 1.2.3.4.
Escape character is '^]'.
Connection closed by foreign host.
```

How it actually looks like when you connect to them is that they accept the connection, but when data is asked for, they return EOS (-1).

Example:
```
import java.net.InetSocketAddress;
import java.net.Socket;

class Test {
    public static void main(String[] args) throws Exception {
        String address = "1.2.3.4";
        int port = 333;
        int timeout = 10000;

        System.out.println("Connecting...");

        Socket socket = new Socket();
        socket.connect(new InetSocketAddress(address, port), timeout);

        System.out.println("Connected, printing...");

        while (true) {
            int data = socket.getInputStream().read();

            if (data == -1) {
                System.out.println("Got -1 for data");
                break;
            } else {
                System.out.println(data);
            }
        }

        System.out.println("Exiting");
    }
}
```
This code results in:
```
Connecting...
Connected, printing...
Got -1 for data
Exiting
```

With the previous examples, lets now cosider how this can be an issue for ExpectIt.
Lets consider the following code:
```
String address = "1.2.3.4";
int port = 333;
int timeout = 10000;

Socket socket = new Socket();
socket.connect(new InetSocketAddress(address, port), timeout);

Expect expect = new ExpectBuilder()
    .withInputs(socket.getInputStream())
    .withTimeout(30, TimeUnit.SECONDS)
    ...
    .build();

expect.expect(regexp("some_regex));
```
The problem is that the above code will result in 30 seconds of 100% CPU usage.

From what I can tell, `SingleInputExpect.java`, line 154, when `matcher.matches(...)` is called, `RegexpMatcher.matches(...)` doesnt use the `isEof` argument at all, therefore always returning `SimpleResult.failure(...)` with `canStopMatching: false`.

This causes the 100% CPU usage for the duration of the `expect.expect(...)` call.

I am not sure if other matchers are affected or not, perhaps other matchers than just `Matchers.regexp` are affected as well.

**Comment by Alexey1Gavrilov** [comment]
Thank you for the bug report! I was able to reproduce.

I'll make a fix and release a new version shortly.

**Comment by Alexey1Gavrilov** [comment]
Can you verify that the fix works for you? 

For doing this, you can clone the repo locally and build the snapshot: mvn clean instlall -DskipTests
Then you can update the dependency version in your project to 0.8.3-SNAPSHOT.

If the fix works for you, I'll release a new version to Maven Central.

**Comment by tomaskir** [comment]
I can confirm the last commits fix the issue for us as well.

Thanks a lot, we really appreciate the fast fix.
And a huge thanks for ExpectIt in general, it's an invaluable tool to us :)

**Comment by Alexey1Gavrilov** [comment]
Thanks! I will release a new version soon. Stay tuned.
