### ISSUE TITLE
expect-pool-* threads not exiting cleanly

### ISSUE THREAD

**Issue by justinleona** [Alexey1Gavrilov/ExpectIt#44]
I'm working on a batch-executable which closely resembles the "Interacting with OS process" example and I noticed the expect-pool-1-thread-2 was blocked indefinitely waiting on input after killing the child process.   

The child process is killed with the following snippet based on the JDK 8 source:

	public static boolean waitFor(long timeout, TimeUnit unit, final Process process) throws InterruptedException, TimeoutException
	{
		long startTime = System.nanoTime();
		long rem = unit.toNanos(timeout);

		do
		{
			try
			{
				process.exitValue();
				return true;
			}
			catch(IllegalThreadStateException ex)
			{
				if( rem > 0 )
					Thread.sleep(Math.min(TimeUnit.NANOSECONDS.toMillis(rem) + 1, 100));
			}
			rem = unit.toNanos(timeout) - (System.nanoTime() - startTime);
		}
		while(rem > 0);
		throw new TimeoutException("Timed out waiting for process");
	}

Expect is wrapped with a try-with-resources block, destroying the process on the above timeout exception.

This has the result of preventing the process from terminating unless System.exit is called.  Attempting to close the streams directly results in a deadlock.  Is it feasible to make the internal threads run as daemon threads as a workaround?  Alternatively can Expect close the input streams as part of it's own cleanup in close?

**Comment by Alexey1Gavrilov** [comment]
May I see the code that uses ExpectIt?
Can you please attach a thread dump the Expect.close has been invoked by try-with-resources block?

**Comment by Alexey1Gavrilov** [comment]
One more thought, I've just fixed an issue with a tight loop when EOF in the input stream occurs which might be related to this issue. Can you please try to build a snapshot out of master head and verify that that the close method still doesn't kill all the threads?

**Comment by justinleona** [comment]
This should be sufficient to reproduce the basic sequence.  

	ProcessBuilder pb = new ProcessBuilder("java", "-cp", classpath, "a.b.c.Example");
	Process process = pb.start();
	try (Expect expect = new ExpectBuilder() //
		.withInputs(process.getInputStream(), process.getErrorStream()) //
		.withOutput(process.getOutputStream()) //
		.withEchoInput(System.out) //
		.withExceptionOnFailure() //
		.withAutoFlushEcho(true) //
		.withTimeout(5, TimeUnit.MINUTES) //wait no longer than 5 minutes between matches
		.build())
	{                        
		expect.expect(contains("foo"));
		expect.sendLine(bar)
        	...
		waitFor(5, TimeUnit.MINUTES, process);
	}
	catch(TimeoutException e)
	{			
		process.destroy();
		throw e;
	}

After the last sendLine the process is expected to run for a while, either terminating normally prior to the timeout or killed so it can resume later.

**Comment by Alexey1Gavrilov** [comment]
Have you tried using 'process.waitFor(5, TimeUnit.MINUTES)'  instead of 'waitFor(5, TimeUnit.MINUTES, process)' ?

**Comment by Alexey1Gavrilov** [comment]
Which OS are you running on?

**Comment by justinleona** [comment]
The timeout variant of process wait for isn't available in Java 7.  

I'm running on Windows 7x64, using IBM JRE 1.7.32 as a standalone process.

Running the latest head I don't see the input threads blocked any longer - I do still see 2 Timer threads waiting, but I can't tell if those are coming from this library or something else.

**Comment by Alexey1Gavrilov** [comment]
Right, the time threads are definitely not from the library.
I'm glad the latest snapshot works as expected. I'll release 0.8.3 to Maven Central soon. Stay tuned.
