### ISSUE TITLE
Inconsistent behavior of Filters.replaceInString(...)

### ISSUE THREAD

**Issue by tomaskir** [Alexey1Gavrilov/ExpectIt#45]
Hello,

I am seeing some strange behavior using `Filters.replaceInString(...)`.
Basically, some input is filtered, and some is not.

Here is runnable code to replicate:
```java
package local.test.expect;

import net.sf.expectit.Expect;
import net.sf.expectit.ExpectBuilder;
import net.sf.expectit.Result;
import net.sf.expectit.filter.Filter;
import net.sf.expectit.filter.Filters;
import net.sf.expectit.matcher.Matchers;

import java.io.IOException;
import java.io.PipedInputStream;
import java.io.PipedOutputStream;
import java.util.concurrent.TimeUnit;

public class Exp {

    public static void main(String[] args) throws IOException {
        PipedInputStream pipedInputStream = new PipedInputStream();
        PipedOutputStream pipedOutputStream = new PipedOutputStream();

        System.out.println("Connecting pipes");
        pipedInputStream.connect(pipedOutputStream);

        System.out.println("Building expect");
        Expect expect = new ExpectBuilder()
                .withInputs(pipedInputStream)
                .withTimeout(30, TimeUnit.SECONDS)
                .withExceptionOnFailure()
                .withInputFilters(myFilter())
                .build();

        System.out.println("Writing data to output");
        for (int i = 0; i < 500; i++) {
            pipedOutputStream.write("removeSome text hereremove\n".getBytes());
        }
        pipedOutputStream.write("done".getBytes());

        System.out.println("Flushing output");
        pipedOutputStream.flush();

        System.out.println("Waiting for 'done'");
        Result r = expect.expect(Matchers.contains("done"));

        System.out.println("Printing data");
        System.out.println(r.getBefore());

        System.out.println("Done");
    }

    private static Filter myFilter() {
        return Filters.replaceInString("remove", "");
    }

}
```

Looking at the output:
```
line 1: Some text here
line 2: Some text here
...
line 37: Some text here
line 38: Some text hereremove
line 39: Some text here
...
line 75: Some text here
line 76: Some text hereremove
line 77: Some text here
...
line 113: Some text here
line 114: Some text hereremove
line 115: Some text here
...
line 417: Some text here
line 418: removeSome text here
line 419: Some text here
...
line 455: Some text here
line 456: removeSome text here
line 457: Some text here
...
line 493: Some text here
line 494: removeSome text here
line 495: Some text here
...
```
As we can see in the output, the filter is behaving rather inconsistently.
Is this potentially an issue in ExpectIt?

Thanks!

**Comment by Alexey1Gavrilov** [comment]
Thanks for the test case!

Currently, the replaceInString filter behaviour depends on when the underlying input stream actually flushes the data. In case of the piped streams, the flush can happen at any time, not necessarily after the end of line. It is possible that the input string in the filter can look like "emove\nSome text here..." if the flush has happened in the middle of the 'remove' word. 

It should work just fine if change 'replaceInString' to 'replaceInBuffer'. The difference is that the replaceInBuffer matches the entire input buffer, no a single string received from the input.

I'll check if I can internally buffer the text input data to avoid this situation.

**Comment by tomaskir** [comment]
Thanks for the update!

`replaceInBuffer` does make it work properly in this test case, but in our full application, we are seeing even worse filtering using `replaceInBuffer` as opposed to using `replaceInString`.

Is there any reason why we would see filtering failing even using `replaceInBuffer`?

Also what is the performance different between `replaceInString` and `replaceInBuffer`?
Sounds like `replaceInBuffer` is much more perf. intensive, since it would do a regexp replace on each addition to the entire input buffer.

**Comment by Alexey1Gavrilov** [comment]
Yes, 'replaceInBuffer' can be tricky since the buffer may grow non-deterministically depending on the input stream. It also has poor performance for obvious reasons.

Let me check how hard is it to add internal single line text buffer to make regexp string filters work consistently.

**Comment by tomaskir** [comment]
Hello,

Any chance for an update on this issue?

Thanks!

**Comment by Alexey1Gavrilov** [comment]
Just I looked at this briefly. It may be possible to optionally force matching only after receiving end-of-line characters but didn't see any obvious and robust way to do so.

I'll take another look when I have more time one-two weeks.

**Comment by Alexey1Gavrilov** [comment]
Tomas,

I've made an effort to solve this problem by introducing a buffered filter which guaranties that the input character stream is processed line by line. 

I may need to add exceptions support based on regex to allow matching of the command line prompts which doesn't end with the line separator.

Please take a look at the example based on your code and try it out: https://github.com/Alexey1Gavrilov/ExpectIt/blob/line-buffered-filter/expectit-core/src/test/java/net/sf/expectit/LineBufferExample.java

**Comment by Alexey1Gavrilov** [comment]
@tomaskir 

I've added support for multiple line separators which should solve the issue with the prompt string that doesn't end with '/n'. Take a look at the example: https://github.com/Alexey1Gavrilov/ExpectIt/blob/line-buffered-filter/expectit-core/src/test/java/net/sf/expectit/LineBufferExample.java

**Comment by Alexey1Gavrilov** [comment]
@tomaskir Please give a try the updated replaceInBuffer filter.
