### ISSUE TITLE
PROMPT question

### ISSUE THREAD

**Issue by magg** [Alexey1Gavrilov/ExpectIt#49]
I've seen this piece of code Matchers.contains( PROMPT ) across some questions.

What do I need to import to use the PROMPT constant?

**Comment by jachinte** [comment]
Hi @magg,
There's no constant PROMPT. When you open an SSH connection, the prompt will be (unless modified) something containing the dollar symbol ($) or the number symbol (#). So, you could use the regexp matcher with a simple expression like `\\$|#`. Then, if you want, you can set a new prompt but that's not necessary.

Example:

```java
Expect expect = ... // build the expect object
expect.expect(regexp("\\$|#")); // wait for the prompt
.. // do something
```
