### ISSUE TITLE
Add pty support (cannot use ExpectIt with qemu)

### ISSUE THREAD

**Issue by toolforger** [Alexey1Gavrilov/ExpectIt#62]
qemu fails with "We need a terminal output" if running with `display curses`

How to reproduce:

Step 1: Download the OS image:
`curl https://download.freebsd.org/ftp/releases/VM-IMAGES/12.0-RELEASE/amd64/Latest/FreeBSD-12.0-RELEASE-amd64.qcow2.xz | xz --decompress >freebsd-original.qcow2`

Step 2: Run this:
```java
	public static void main(String[] args) throws Exception {
		File currentDir = new File("../qemu/install/bin").getCanonicalFile();
		System.out.println ("cd " + currentDir);
		String[] cmd = {
				"qemu-system-x86_64", // Change this to match your distro's conventions
				"-display", "curses",
				"-snapshot",
				"freebsd-original.qcow2"
		};
		System.out.println (String.join(" ", cmd));
		
		Process process = new ProcessBuilder(cmd)
				.directory(currentDir)
				.inheritIO()
				.start();

		try (Expect expect = new ExpectBuilder()
				.withInputs(process.getInputStream(), process.getErrorStream())
				.withOutput(process.getOutputStream())
				.withTimeout(90, TimeUnit.SECONDS)
//				.withExceptionOnFailure()
				.withCharset(StandardCharsets.US_ASCII)
				.withEchoInput(System.out)
				.withEchoOutput(System.out)
				.build())
		{
			expect.expect(exact("Autoboot in"));
		};
	}
```

The error originates from `static void curses_display_init(DisplayState *, , DisplayOptions *)` in `ui/curses.c`, line 714: https://git.qemu.org/?p=qemu.git;a=blob;f=ui/curses.c;h=fb63945188b2affe70ed23c76231456af07afd36;hb=HEAD#l714

```C
    if (!isatty(1)) {
        fprintf(stderr, "We need a terminal output\n");
        exit(1);
    }
```

i.e. qemu checks if stdout (file descriptor 1) is a tty and refuses to start if not.

This can be avoided by using a pty, see https://en.wikipedia.org/wiki/Pseudo_terminal for an introduction.
I did a bit of digging around and found several JNA-based libraries that give access to ptys, with code for different operating systems; I didn't take notes but I can find them again if you are interested.

**Comment by agavrilov76** [comment]
I'm not sure that the Expect java library should deal with direct PTY access. Have you tried to combine ExpectIt with [Pty for Java ](jhttps://github.com/JetBrains/pty4j) from JetBrains? Looks like to should work just fine since it gives the access to standard output streams.

**Comment by toolforger** [comment]
I seem to have taken a look at it: the browser still remembers it, even though I don't.
I can't recall what exactly failed with it; I guess either qemu wouldn't recognize the pty anyway, or it didn't occur to me to try and combine Expectit with pty4j.
The readme mentions that Java has issues with forking, and that pty4j uses forking. Today, I wouldn't want to use code like that, tough obviously YMMV.

Generally speaking:
1) I do think that any expect-like library should offer using ptys; after all, expect does, and the very purpose of expect is to make interactive software scriptable; pty-using software is just one (important) kind of interactive. That's in favor of implementing it, be it in the form of making a pty4j-expect library that pulls in both pty4j and ExpectIt and offers whatever glue code may be necessary, be it in the form of new code.
2) My personal use case has vanished, since I have given up on qemu anyway. So feel free to close this :-)
3) I have come to the conclusion that getting ptys right may be a lot of effort, so that's another reason for you to close the request ;-)

**Comment by toolforger** [comment]
Oops, misclick. Feel free to reopen if you want to do implementing anyway.
